version: 0.0
os: linux
files:
  - source: /scripts/docker-compose.yml
    destination: /home/ubuntu/dst-pipeline/scripts
  - source: /scripts/stop_and_remove_containers.sh
    destination: /home/ubuntu/dst-pipeline/scripts
  - source: /scripts/start_containers.sh
    destination: /home/ubuntu/dst-pipeline/scripts
  - source: /scripts/copy_from_s3.sh
    destination: /home/ubuntu/dst-pipeline/scripts
  - source: /scripts/load_image.sh
    destination: /home/ubuntu/dst-pipeline/scripts

hooks:
  BeforeInstall:
    - location: scripts/copy_from_s3.sh
      timeout: 600
      runas: ubuntu

  Install:
    - location: scripts/load_image.sh
      timeout: 600
      runas: ubuntu

  AfterInstall:
    - location: scripts/stop_and_remove_containers.sh
      runas: ubuntu

  ApplicationStart:
    - location: scripts/start_containers.sh
      runas: ubuntu
  