version: 0.2
phases:
  pre_build:
    commands:
      - echo pre-building - login to docker....
      - docker login -u "dmcdstservice" --password "P7a5nwcczsr"

      
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t nhlbi-bdc-dmc-dst_bdc-dashboard-app api
      - docker save nhlbi-bdc-dmc-dst_bdc-dashboard-app > nhlbi-bdc-dmc-dst_bdc-dashboard-app-dev.tar
      - aws s3 cp nhlbi-bdc-dmc-dst_bdc-dashboard-app-dev.tar s3://bdc-dmc-dst-dashboard-app/nhlbi-bdc-dmc-dst_bdc-dashboard-app-dev.tar
      
      
  post_build:
    commands:
      - echo Nothing for post build...

artifacts:
  files:
    - appspec.yml
    - scripts/**
    - api/.env.sample
  name: BuildArtifact
