version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 219318155624.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t pythodjangotest .
      - docker tag pythodjangotest:latest 219318155624.dkr.ecr.us-east-1.amazonaws.com/pythodjangotest:latest
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 219318155624.dkr.ecr.us-east-1.amazonaws.com/pythodjangotest:latest