version: 0.2
phases:
  pre_build:
    commands:
      - echo pre-building nothing for now...
      
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - touch nhlbi-bdc-dmc-dst_bdc-dashboard-app.tar
      - aws s3 cp nhlbi-bdc-dmc-dst_bdc-dashboard-app.tar s3://codepipeline-us-east-1-583102800307/ --sse aws:kms sse-kms-key-id 903ed33e-2185-4e66-846a-37b022b86502
      
  post_build:
    commands:
      - echo Nothing for post build...

artifacts:
  files:
    - appspec.yml
    - scripts/**
  name: BuildArtifact