version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 099963124704.dkr.ecr.us-east-1.amazonaws.com
     
      
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t nhlbi-bdc-dmc-dst_bdc-dashboard-app api
      - echo Tagging the Docker image...
      - docker tag nhlbi-bdc-dmc-dst_bdc-dashboard-app:latest 099963124704.dkr.ecr.us-east-1.amazonaws.com/dst/nhlbi-bdc-dmc-dst_bdc-dashboard-app:latest

  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push 099963124704.dkr.ecr.us-east-1.amazonaws.com/dst/nhlbi-bdc-dmc-dst_bdc-dashboard-app:latest
      - echo Build and push to ECR completed.

artifacts:
  files:
    - appspec.yml
    - scripts/**
    - api/.env.sample
  name: BuildArtifact
