# Generated by Django 4.1.4 on 2025-02-12 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_historicalticket_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='HistoricalTicket',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
