version: "3.8"

networks:
  bdcat:

services:
  database:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      # NOTE: Deployment
      # Uncomment appropriate password for Deployment or Development
      # Deployment Postgres password
      # POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # Set a password based on user set in development postgres delpoyment
      POSTGRES_PASSWORD: tracker_password
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - bdcat
    ports:
      - "5432:5432"
    volumes:
      - "${POSTGRES_DATA_DIR}:/var/lib/postgresql/data"
