services:
  bdc-dashboard-db:
    container_name: bdc-dashboard-db
    image: postgres:latest
    restart: always
    env_file:
      - api/.env
    volumes:
      - /var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - "5432:5432"


  bdc-dashboard-app:
    image: 099963124704.dkr.ecr.us-east-1.amazonaws.com/dst/nhlbi-bdc-dmc-dst_bdc-dashboard-app:latest
    container_name: bdc-dashboard-app
    environment:
      - DEBUG=True
    env_file:
      - api/.env
    expose:
      - 8000
      - 2222
    ports:
      - "8000:8000"
   
